name: "publish-release"

on:
  push:
    branches:
      - "stable"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Get name from info.json (stable)
      id: getname
      uses: ashley-taylor/read-json-property-action@v1.2
      with:
        path: info.json
        property: name
    - name: Get version from info.json (stable)
      id: getversion
      uses: ashley-taylor/read-json-property-action@v1.2
      with:
        path: info.json
        property: version
    - name: Echo name
      run: echo ${{ steps.getname.outputs.value }}
    - name: Echo version
      run: echo ${{ steps.getversion.outputs.value }}
    - name: Manage files
      run: |
        mkdir -p build/${{ steps.getname.outputs.value }}
        rsync -av --progress . build/${{ steps.getname.outputs.value }} --exclude build
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        directory: "./build"
        # path: "./${{ steps.getname.outputs.value }}"
        filename: "${{ steps.getname.outputs.value }}_${{ steps.getversion.outputs.value }}.zip"
        exclusions: '*.git* *.md *.sh *.vscode *.releaserc'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        # updateOnlyUnreleased: true # Can we have production at home? Production at home:
        tag: "v${{ steps.getversion.outputs.value }}"
        artifacts: "./build/${{ steps.getname.outputs.value }}_${{ steps.getversion.outputs.value }}.zip"
